[package]
name = "cags"
version = "0.1.0"
authors = ["Alexandre Duc <alexandre.aduc@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
read_input = "0.8"
lazy_static = "1.4.0"
serde_json = "1.0"
